'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { ArrowUpRight, Check, ChevronDown, Circle, FileText, Globe2, Menu, ShieldCheck, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { asset, navItems } from '@/lib/a2z-data'

export function Logo() { return <Link href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground text-sm shadow-sm">A2</span><span>A2Z <span className="text-muted-foreground font-normal">Edit</span></span></Link> }
export function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const [open, setOpen] = useState(false)
  return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo/><nav className="hidden items-center gap-1 md:flex">{navItems.map(item => <Link key={item.href} href={item.href} className={`rounded-lg px-3 py-2 text-sm transition-colors ${path === item.href ? 'bg-secondary text-foreground font-medium' : 'text-muted-foreground hover:text-foreground'}`}>{item.label}</Link>)}</nav><div className="flex items-center gap-3"><span className="hidden rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground sm:inline-flex"><Circle className="mr-1.5 mt-0.5 size-2 fill-emerald-500 text-emerald-500"/>Pre-revenue asset</span><Link href="/deal-room" className="hidden rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90 sm:inline-flex">Request details <ArrowUpRight className="ml-1.5 size-4"/></Link><button aria-label="Open menu" onClick={() => setOpen(!open)} className="rounded-lg border border-border p-2 md:hidden">{open ? <X className="size-5"/> : <Menu className="size-5"/>}</button></div></div>{open && <nav className="flex flex-col gap-1 border-t border-border px-5 py-3 md:hidden">{navItems.map(item => <Link onClick={() => setOpen(false)} key={item.href} href={item.href} className="rounded-lg px-3 py-2.5 text-sm text-muted-foreground">{item.label}</Link>)}</nav>}</header><main>{children}</main><footer className="border-t border-border bg-secondary/40"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><Logo/><p className="mt-3 text-xs">A digital toolkit prepared for acquisition.</p></div><p className="text-xs">Built and documented by <span className="font-medium text-foreground">{asset.developer}</span> · {new Date().getFullYear()}</p></div></footer></div>
}
export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><Sparkles className="size-3.5"/>{children}</p> }
export function PageHeader({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="border-b border-border bg-secondary/30"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8 lg:py-20"><Eyebrow>{eyebrow}</Eyebrow><h1 className="max-w-3xl text-balance text-4xl font-semibold tracking-tight sm:text-5xl">{title}</h1>{children && <div className="mt-5 max-w-2xl text-pretty leading-7 text-muted-foreground">{children}</div>}</div></div> }
export function Stat({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="border-l-2 border-primary pl-4"><p className="text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-sm font-medium">{label}</p>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</div> }
export function SectionTitle({ title, children }: { title: string; children?: React.ReactNode }) { return <div className="mb-8 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><h2 className="text-2xl font-semibold tracking-tight">{title}</h2>{children && <p className="max-w-md text-sm leading-6 text-muted-foreground sm:text-right">{children}</p>}</div> }
export function TrustRow() { return <div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary"/>Transfer-ready</span><span className="flex items-center gap-2"><Globe2 className="size-4 text-primary"/>Multi-platform</span><span className="flex items-center gap-2"><FileText className="size-4 text-primary"/>268 content pages</span></div> }
export function Accordion({ question, answer }: { question: string; answer: string }) { const [open, setOpen] = useState(false); return <div className="border-b border-border"><button className="flex w-full items-center justify-between gap-4 py-5 text-left font-medium" onClick={() => setOpen(!open)} aria-expanded={open}>{question}<ChevronDown className={`size-4 shrink-0 text-muted-foreground transition-transform ${open ? 'rotate-180' : ''}`}/></button>{open && <p className="pb-5 pr-8 text-sm leading-6 text-muted-foreground">{answer}</p>}</div> }
export const CheckItem = ({ children }: { children: React.ReactNode }) => <li className="flex gap-3 text-sm leading-6 text-muted-foreground"><Check className="mt-1 size-4 shrink-0 text-primary"/>{children}</li>
